server:
  port: 8080

spring:
  datasource:
    driver: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/library_management_system
    username: root
    password: JtscH7R8

  jpa:
    hibernate:
      ddl-auto: update
